1;FIXME Per the RegionFactory class Javadoc;cache-jbosscache/src/main/java/org/hibernate/cache/jbc2/JBossCacheRegionFactory.java;c49ef2e2f;cache-jbosscache/src/main/java/org/hibernate/cache/jbc2/JBossCacheRegionFactory.java;d2c88d55d
2;TODO: joinKeyColumnName & foreignKeyColumnName should be called either here or at a;code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
3;// 'hibernate.temp.use_jdbc_metadata_defaults' is a temporary magic value;code/core/src/main/java/org/hibernate/cfg/SettingsFactory.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/SettingsFactory.java;91d444423
4;// Do we need to drop constraints before dropping tables in this dialect?;code/core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;87e3f0fd2
5;// Does this dialect support check constraints?;code/core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;5fc70fc5a
6;// Does this dialect support FOR UPDATE OF;code/core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;5fc70fc5a
7;// Does this dialect support the FOR UPDATE syntax?;code/core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;5fc70fc5a
8;// Does this dialect support the Oracle-style FOR UPDATE NOWAIT syntax?;code/core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;5fc70fc5a
9;// Does this dialect support the UNIQUE column syntax?;code/core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;49c8a8e4f
10;// FIXME hack to work around fact that calling;cache-infinispan/src/main/java/org/hibernate/cache/infinispan/util/CacheHelper.java;9ccd912bd;cache-infinispan/src/main/java/org/hibernate/cache/infinispan/util/CacheHelper.java;9e7e49d1f
11;// FIXME Hacky workaround to JBCACHE-1202;cache-jbosscache2/src/main/java/org/hibernate/cache/jbc2/BasicRegionAdapter.java;161e5cc19;cache-jbosscache2/src/main/java/org/hibernate/cache/jbc2/BasicRegionAdapter.java;834be2837
12;// get the right object from the list ... would it be easier to just call getEntity() ??;code/core/src/main/java/org/hibernate/loader/entity/BatchingEntityLoader.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/loader/entity/BatchingEntityLoader.java;06b0faaf5
13;// hack/workaround as sqlquery impl depend on having a key.;code/core/src/main/java/org/hibernate/cfg/ResultSetMappingBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/ResultSetMappingBinder.java;9caca0ce3
14;// implicit joins are always(?) ok to reuse;hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java;a0663f0d6;hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java;153c4e32e
15;// is this really necessary?;code/core/src/main/java/org/hibernate/type/AbstractBynaryType.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/type/AbstractBynaryType.java;7308e14fe
16;// NONE might be a better option moving forward in the case of callable;code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
17;// orphans should not be deleted during copy??;code/core/src/main/java/org/hibernate/engine/CascadingAction.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/engine/CascadingAction.java;3402ba3a6
18;// perhaps this should be an exception since it is only ever used;code/core/src/main/java/org/hibernate/event/def/DefaultMergeEventListener.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/event/def/DefaultMergeEventListener.java;fe8c7183d
19;// short cut check...;commons-annotations/src/main/java/org/hibernate/annotations/common/util/StringHelper.java;82e5fa8c7;commons-annotations/src/main/java/org/hibernate/annotations/common/util/StringHelper.java;59ec451c2
20;// short-circuit for performance...;hibernate-core/src/main/java/org/hibernate/impl/AbstractQueryImpl.java;0013a90d2;hibernate-core/src/main/java/org/hibernate/impl/AbstractQueryImpl.java;d1515a291
21;// TBD should this be varbinary($1)?;code/core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/dialect/Cache71Dialect.java;5fc70fc5a
22;// this class has no proxies (so do a shortcut);hibernate-core/src/main/java/org/hibernate/event/internal/DefaultResolveNaturalIdEventListener.java;eecee618c;hibernate-core/src/main/java/org/hibernate/event/internal/DefaultResolveNaturalIdEventListener.java;f74c5a7fa
23;// This inner class implements a case statement....perhaps im being a bit over-clever here;code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
24;// this is done here 'cos we might only know the type here (ugly!);code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
25;// todo : better to handle dynamic filters through implicit DynamicFilterParameterSpecification;code/core/src/main/java/org/hibernate/loader/hql/QueryLoader.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/loader/hql/QueryLoader.java;6cabc326b
26;// todo : currently expects that the individual with expressions apply to the same sql table join;code/core/src/main/java/org/hibernate/hql/ast/HqlSqlWalker.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/hql/ast/HqlSqlWalker.java;a9b1425f3
27;// todo : potentially look at optimizing these two arrays;hibernate-core/src/main/java/org/hibernate/engine/internal/MutableEntityEntry.java;5c4dacb83;hibernate-core/src/main/java/org/hibernate/engine/internal/MutableEntityEntry.java;3e5a8b660
28;// todo : remove;hibernate-core/src/main/java/org/hibernate/metamodel/source/internal/MetadataImpl.java;baeb6dc40;hibernate-core/src/main/java/org/hibernate/metamodel/source/internal/MetadataImpl.java;66ce8b7fb
29;// TODO : remove these last two as batcher is no longer managing connections;code/core/src/main/java/org/hibernate/jdbc/Batcher.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/jdbc/Batcher.java;97fef96b9
30;// todo : remove this and just have subclasses use Isolater/IsolatedWork directly...;code/core/src/main/java/org/hibernate/engine/TransactionHelper.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/engine/TransactionHelper.java;08d9fe211
31;// todo : should really move this log statement to CollectionType;code/core/src/main/java/org/hibernate/engine/loading/LoadContexts.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/engine/loading/LoadContexts.java;a9b1425f3
32;// todo : we can remove this once the deprecated ctor can be made private...;core/src/main/java/org/hibernate/transform/DistinctRootEntityResultTransformer.java;1851bffce;core/src/main/java/org/hibernate/transform/DistinctRootEntityResultTransformer.java;a6ca833e2
33;// todo : what else to do here?;code/core/src/main/java/org/hibernate/bytecode/cglib/ProxyFactoryFactoryImpl.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/bytecode/cglib/ProxyFactoryFactoryImpl.java;82d2ef4b1
34;// todo : what is the implication of this?;code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
35;// todo : YUCK!!!;hibernate-core/src/main/java/org/hibernate/tuple/entity/PojoEntityTuplizer.java;8a5415d36;hibernate-core/src/main/java/org/hibernate/tuple/entity/PojoEntityTuplizer.java;66ce8b7fb
36;// TODO: is it really neceassry to provide Configuration to CollectionPersisters ?;hibernate-core/src/main/java/org/hibernate/persister/spi/PersisterFactory.java;ddfcc44d7;hibernate-core/src/main/java/org/hibernate/persister/spi/PersisterFactory.java;996d56773
37;// TODO: it would be better if this was done at the higher level by Printer;code/core/src/main/java/org/hibernate/type/CollectionType.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/type/CollectionType.java;4a4f636ca
38;// TODO: It would be really;code/core/src/main/java/org/hibernate/persister/entity/PropertyMapping.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/persister/entity/PropertyMapping.java;af1061a42
39;// TODO: this is a bit of copy/paste from IndexedCollection.createPrimaryKey();code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
40;// todo: this might really even be moved into the cfg package and used as the basis for all things which are configurable.;code/core/src/main/java/org/hibernate/exception/Configurable.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/exception/Configurable.java;a806626a2
41;// VERY IMPORTANT!!!! - This class needs to be free of any static references;code/core/src/main/java/org/hibernate/intercept/FieldInterceptionHelper.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/intercept/FieldInterceptionHelper.java;19791a6c7
42;// we have to set up the table later!! yuck;code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
43;// why does this matter?;hibernate-core/src/main/java/org/hibernate/loader/internal/AbstractLoadQueryImpl.java;b3791bc3c;hibernate-core/src/main/java/org/hibernate/loader/internal/AbstractLoadQueryImpl.java;8e2f2a9da
44;//ick!;commons-annotations/src/main/java/org/hibernate/annotations/common/util/StringHelper.java;82e5fa8c7;commons-annotations/src/main/java/org/hibernate/annotations/common/util/StringHelper.java;59ec451c2
45;//Icky workaround for MySQL bug:;code/core/src/main/java/org/hibernate/cfg/Configuration.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java;377c30007
46;//is this ok?;code/core/src/main/java/org/hibernate/property/Dom4jAccessor.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/property/Dom4jAccessor.java;4a4f636ca
47;//shortcut;code/core/src/main/java/org/hibernate/mapping/SimpleValue.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java;9caca0ce3
48;"//TODO: better to degrade to lazy=""false"" if uninstrumented";code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
49;//TODO: code duplication with JoinedSubclassEntityPersister;hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java;5457b6c70;hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java;66ce8b7fb
50;//TODO: copy/paste from insertRows();code/core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java;129c0f134
51;//TODO: copy/paste from recreate();code/core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java;129c0f134
52;//TODO: deprecated;code/core/src/main/java/org/hibernate/mapping/Column.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/mapping/Column.java;d7cc102b0
53;//TODO: design new lifecycle for ProxyFactory;hibernate-core/src/main/java/org/hibernate/tuple/entity/DynamicMapEntityTuplizer.java;8a5415d36;hibernate-core/src/main/java/org/hibernate/tuple/entity/DynamicMapEntityTuplizer.java;66ce8b7fb
54;//TODO: get SQL rendering out of this package!;code/core/src/main/java/org/hibernate/criterion/BetweenExpression.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/criterion/BetweenExpression.java;8c28ba846
55;//TODO: ideally we need the construction of PropertyAccessor to take the following:;code/core/src/main/java/org/hibernate/property/PropertyAccessorFactory.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/property/PropertyAccessorFactory.java;9e063ffa2
56;//TODO: implement caching?! proxies?!;code/core/src/main/java/org/hibernate/type/EntityType.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/type/EntityType.java;1c3491445
57;//TODO: improve this hack!;code/core/src/main/java/org/hibernate/mapping/UniqueKey.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/mapping/UniqueKey.java;f4c36a10f
58;//TODO: inefficient;hibernate-core/src/main/java/org/hibernate/persister/walking/spi/AssociationKey.java;a102bf2c3;hibernate-core/src/main/java/org/hibernate/persister/walking/spi/AssociationKey.java;18079f346
59;//TODO: is there a more elegant way than downcasting?;code/core/src/main/java/org/hibernate/persister/collection/NamedQueryCollectionInitializer.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/persister/collection/NamedQueryCollectionInitializer.java;87e3f0fd2
60;//TODO: is this right??;code/core/src/main/java/org/hibernate/type/AnyType.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/type/AnyType.java;dc7cdf9d8
61;//TODO: need some caching scheme? really comes down to decision;code/core/src/main/java/org/hibernate/property/PropertyAccessorFactory.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/property/PropertyAccessorFactory.java;4a4f636ca
62;//TODO: put this stuff back in to read snapshot from;code/core/src/main/java/org/hibernate/event/def/DefaultSaveOrUpdateEventListener.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/event/def/DefaultSaveOrUpdateEventListener.java;a9b1425f3
63;//TODO: really bad;code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
64;//TODO: redesign how PropertyAccessors are acquired...;hibernate-core/src/main/java/org/hibernate/tuple/entity/AbstractEntityTuplizer.java;8a5415d36;hibernate-core/src/main/java/org/hibernate/tuple/entity/AbstractEntityTuplizer.java;66ce8b7fb
65;//TODO: reuse the PostLoadEvent...;hibernate-core/src/main/java/org/hibernate/event/internal/DefaultResolveNaturalIdEventListener.java;eecee618c;hibernate-core/src/main/java/org/hibernate/event/internal/DefaultResolveNaturalIdEventListener.java;f74c5a7fa
66;//TODO: Somehow add the newly created foreign keys to the internal collection;code/core/src/main/java/org/hibernate/cfg/Configuration.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java;9caca0ce3
67;//TODO: suck this into initLaziness!;code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
68;//TODO: this is a bit arbitrary;code/core/src/main/java/org/hibernate/type/EntityType.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/type/EntityType.java;9938937fe
69;//TODO: this is temporary in that the end result will probably not take a Property reference per-se.;hibernate-core/src/main/java/org/hibernate/property/PropertyAccessorFactory.java;1d26ac1e1;hibernate-core/src/main/java/org/hibernate/property/PropertyAccessorFactory.java;9e063ffa2
70;//TODO: to handle concurrent writes correctly;code/core/src/main/java/org/hibernate/cache/UpdateTimestampsCache.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cache/UpdateTimestampsCache.java;4aa9cbe5b
71;//TODO: we should provide some way to get keys of collection of statistics to make it easier to retrieve from a GUI perspective;code/core/src/main/java/org/hibernate/stat/StatisticsImpl.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/stat/StatisticsImpl.java;f93d1412a
72;//use of trim() here is ugly?;code/core/src/main/java/org/hibernate/loader/Loader.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/loader/Loader.java;c46daa4cf
73;//yuck!;code/core/src/main/java/org/hibernate/criterion/Example.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/criterion/Example.java;8c28ba846
74;"but needed for collections with a ""."" node mapping";code/core/src/main/java/org/hibernate/property/Dom4jAccessor.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/property/Dom4jAccessor.java;4a4f636ca
75;cos it depends upon ordering of mapping doc;code/core/src/main/java/org/hibernate/cfg/HbmBinder.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/cfg/HbmBinder.java;9caca0ce3
76;since getTypeName() actually throws an exception!;code/core/src/main/java/org/hibernate/dialect/function/CastFunction.java;d8d6d82e3;hibernate-core/src/main/java/org/hibernate/dialect/function/CastFunction.java;c97075c3c